---
title: "mothur sens.spec()"
output:
  github_document:
    html_preview: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      fig.path = 'figures/',
                      dpi = 300)
```
```{r deps, message=FALSE, warning=FALSE}
library(here)
library(tidyverse)
set.seed(20211014)
```

```{r summary}
dat <- read_tsv(here('results', 'sensspec_concat.tsv')) %>%
  mutate(paper = case_when(dataset == 'miseq_1.0_01' ~ 'Schloss_Cluster_PeerJ_2015',
                           dataset == 'mouse' ~ 'Sovacool_OptiFit_2021',
                           TRUE ~ 'unknown'),
         method = case_when(cluster_method == 'vdgc' ~ 'VSEARCH de novo',
                            cluster_method == 'cvsearch' ~ 'VSEARCH closed ref',
                            TRUE ~ 'unknown'))
dat %>%
  select(dataset, cluster_method, mothur_version, filetype, mcc, num_otus) %>%
  knitr::kable()
```


```{r plot_mcc}
dat %>% ggplot(aes(x=mothur_version, y=mcc, color=dataset, shape=filetype)) +
  geom_point(position = position_jitter(width=0.1, height = 0),
             size = 5, alpha=0.7) +
  facet_wrap("cluster_method") +
  ylim(0,1) +
  theme_bw()
```

```{r for_lab_mtg}
dat %>% ggplot(aes(x=mothur_version, y=mcc, color=paper, shape=filetype)) +
  geom_point(position = position_jitter(width=0.1, height = 0),
             size = 5, alpha=0.7) +
  facet_wrap('method') +
  ylim(0,1) +
  theme_bw() +
  theme(legend.position = 'top',
        legend.title = element_blank())
```

